parameters:
    grossum_faq.faq.admin.class:   Grossum\FaqBundle\Admin\FaqAdmin
    grossum_faq.faq.entity.class:  Grossum\FaqBundle\Entity\Faq
    grossum_faq.faq.manager.class: Grossum\FaqBundle\Entity\EntityManager\FaqManager
