Grossum\FaqBundle\Entity\BaseFaq:
    properties:
        question:
            - NotBlank: ~
        answer:
            - NotBlank: ~
        position:
            - NotBlank: ~
            - GreaterThanOrEqual:
                value: 1
